version: '3.9'

services:
  chromedriver:
    image: drupalci/chromedriver:production
    privileged: true
    networks:
      - internal
    expose:
      - 4444
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=""

  selenium:
    image: selenium/standalone-chrome:latest
    expose:
      - 4444
    networks:
      - internal

  testrunner:
    container_name: testrunner
    image: golang:latest
    environment:
      - CHROMEDRIVER_ADDR=chromedriver:4444
      - SELENIUM_ADDR=selenium:4444
      - GOPHERJS_SERVER_ADDR=testrunner:8080
    ports:
      - 8080:8080
      - 9090:9090
      - 9095:9095
      - 9100:9100
      - 9105:9105
    depends_on:
      - chromedriver
      - selenium
    networks:
      - internal
    command: sleep infinity
    
networks:
  internal:
    driver: bridge